/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const GalleryImageId = IDL.Nat;
export const Category = IDL.Variant({
  'jewellery' : IDL.Null,
  'gluelessWig' : IDL.Null,
  'headbandWig' : IDL.Null,
});
export const ProductId = IDL.Nat;
export const ServiceId = IDL.Nat;
export const TestimonialId = IDL.Nat;
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const GalleryImage = IDL.Record({
  'id' : GalleryImageId,
  'displayOrder' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'caption' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : Category,
  'priceKES' : IDL.Nat,
});
export const Service = IDL.Record({
  'id' : ServiceId,
  'displayOrder' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'iconName' : IDL.Text,
  'priceFrom' : IDL.Opt(IDL.Text),
});
export const SiteSettings = IDL.Record({
  'instagramHandle' : IDL.Text,
  'instagramPosts' : IDL.Nat,
  'instagramFollowers' : IDL.Nat,
  'instagramFollowing' : IDL.Nat,
  'whatsappNumber' : IDL.Text,
  'aboutText' : IDL.Text,
  'heroTagline' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'id' : TestimonialId,
  'review' : IDL.Text,
  'clientName' : IDL.Text,
  'avatarInitials' : IDL.Text,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createGalleryImage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [GalleryImageId],
      [],
    ),
  'createProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, Category, IDL.Text, IDL.Bool],
      [ProductId],
      [],
    ),
  'createService' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Nat],
      [ServiceId],
      [],
    ),
  'createTestimonial' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [TestimonialId],
      [],
    ),
  'deleteGalleryImage' : IDL.Func([GalleryImageId], [], []),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'deleteService' : IDL.Func([ServiceId], [], []),
  'deleteTestimonial' : IDL.Func([TestimonialId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getSiteSettings' : IDL.Func([], [IDL.Opt(SiteSettings)], ['query']),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateGalleryImage' : IDL.Func(
      [GalleryImageId, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'updateProduct' : IDL.Func(
      [ProductId, IDL.Text, IDL.Text, IDL.Nat, Category, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'updateService' : IDL.Func(
      [ServiceId, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'updateSiteSettings' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'updateTestimonial' : IDL.Func(
      [TestimonialId, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const GalleryImageId = IDL.Nat;
  const Category = IDL.Variant({
    'jewellery' : IDL.Null,
    'gluelessWig' : IDL.Null,
    'headbandWig' : IDL.Null,
  });
  const ProductId = IDL.Nat;
  const ServiceId = IDL.Nat;
  const TestimonialId = IDL.Nat;
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const GalleryImage = IDL.Record({
    'id' : GalleryImageId,
    'displayOrder' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'caption' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : Category,
    'priceKES' : IDL.Nat,
  });
  const Service = IDL.Record({
    'id' : ServiceId,
    'displayOrder' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'iconName' : IDL.Text,
    'priceFrom' : IDL.Opt(IDL.Text),
  });
  const SiteSettings = IDL.Record({
    'instagramHandle' : IDL.Text,
    'instagramPosts' : IDL.Nat,
    'instagramFollowers' : IDL.Nat,
    'instagramFollowing' : IDL.Nat,
    'whatsappNumber' : IDL.Text,
    'aboutText' : IDL.Text,
    'heroTagline' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'id' : TestimonialId,
    'review' : IDL.Text,
    'clientName' : IDL.Text,
    'avatarInitials' : IDL.Text,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createGalleryImage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [GalleryImageId],
        [],
      ),
    'createProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, Category, IDL.Text, IDL.Bool],
        [ProductId],
        [],
      ),
    'createService' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Nat],
        [ServiceId],
        [],
      ),
    'createTestimonial' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [TestimonialId],
        [],
      ),
    'deleteGalleryImage' : IDL.Func([GalleryImageId], [], []),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'deleteService' : IDL.Func([ServiceId], [], []),
    'deleteTestimonial' : IDL.Func([TestimonialId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getSiteSettings' : IDL.Func([], [IDL.Opt(SiteSettings)], ['query']),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateGalleryImage' : IDL.Func(
        [GalleryImageId, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'updateProduct' : IDL.Func(
        [ProductId, IDL.Text, IDL.Text, IDL.Nat, Category, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'updateService' : IDL.Func(
        [ServiceId, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'updateSiteSettings' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'updateTestimonial' : IDL.Func(
        [TestimonialId, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };