/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'jewellery' : null } |
  { 'gluelessWig' : null } |
  { 'headbandWig' : null };
export interface GalleryImage {
  'id' : GalleryImageId,
  'displayOrder' : bigint,
  'imageUrl' : string,
  'caption' : string,
}
export type GalleryImageId = bigint;
export interface Product {
  'id' : ProductId,
  'name' : string,
  'isAvailable' : boolean,
  'description' : string,
  'imageUrl' : string,
  'category' : Category,
  'priceKES' : bigint,
}
export type ProductId = bigint;
export interface Service {
  'id' : ServiceId,
  'displayOrder' : bigint,
  'name' : string,
  'description' : string,
  'iconName' : string,
  'priceFrom' : [] | [string],
}
export type ServiceId = bigint;
export interface SiteSettings {
  'instagramHandle' : string,
  'instagramPosts' : bigint,
  'instagramFollowers' : bigint,
  'instagramFollowing' : bigint,
  'whatsappNumber' : string,
  'aboutText' : string,
  'heroTagline' : string,
}
export interface Testimonial {
  'id' : TestimonialId,
  'review' : string,
  'clientName' : string,
  'avatarInitials' : string,
  'rating' : bigint,
}
export type TestimonialId = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createGalleryImage' : ActorMethod<[string, string, bigint], GalleryImageId>,
  'createProduct' : ActorMethod<
    [string, string, bigint, Category, string, boolean],
    ProductId
  >,
  'createService' : ActorMethod<
    [string, string, [] | [string], string, bigint],
    ServiceId
  >,
  'createTestimonial' : ActorMethod<
    [string, string, bigint, string],
    TestimonialId
  >,
  'deleteGalleryImage' : ActorMethod<[GalleryImageId], undefined>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'deleteService' : ActorMethod<[ServiceId], undefined>,
  'deleteTestimonial' : ActorMethod<[TestimonialId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGalleryImages' : ActorMethod<[], Array<GalleryImage>>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'getServices' : ActorMethod<[], Array<Service>>,
  'getSiteSettings' : ActorMethod<[], [] | [SiteSettings]>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateGalleryImage' : ActorMethod<
    [GalleryImageId, string, string, bigint],
    undefined
  >,
  'updateProduct' : ActorMethod<
    [ProductId, string, string, bigint, Category, string, boolean],
    undefined
  >,
  'updateService' : ActorMethod<
    [ServiceId, string, string, [] | [string], string, bigint],
    undefined
  >,
  'updateSiteSettings' : ActorMethod<
    [string, string, string, string, bigint, bigint, bigint],
    undefined
  >,
  'updateTestimonial' : ActorMethod<
    [TestimonialId, string, string, bigint, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];